---
port: 8686
data: "./data"
src: "."
database: "local"
userManagement: true
region: ""
domainName: ""
clientId: ""
redirectUri: ""
logOutUri: ""
clientSecret: ""
awsTokenURL: ""
awsJwkUrl : ""
userPoolID: ""
...
